#ifndef GLOBAL_H
#define GLOBAL_H

enum exitCodes {
    BLUETOOTH_OFF = 1,
    NOT_ALL_REQUIRED_DEVICES_FOUND,
    DISCOVERY_ERROR,
    PAIRING_ERROR,
    BLE_ERROR,
    CHARACTERISTIC_NOT_FOUND,
    PAYLOAD_TOO_SMALL,
};

#endif // GLOBAL_H
